M48
; DRILL file {KiCad 8.0.7} date 2025-02-20T16:39:15-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-20T16:39:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X139.63Y-121.02
X145.41Y-121.02
T2
X120.0Y-38.0
X120.0Y-121.0
X173.0Y-38.0
X173.0Y-121.0
M30
